=== mercysho/CO458-XML/CV/CV.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="CV">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="PersonalDetails">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="FullName" type="xs:string" />
              <xs:element name="Email" type="xs:string" />
              <xs:element name="PhoneNumber" type="xs:unsignedLong" />
              <xs:element name="Photo" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Employment">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="Job">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Start" type="xs:unsignedShort" />
                    <xs:element name="End" type="xs:string" />
                    <xs:element name="Company" type="xs:string" />
                    <xs:element name="Duties" type="xs:string" />
                    <xs:element name="Description" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Education">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="Insitution">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Subjects">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Subject">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Start" type="xs:unsignedShort" />
                                <xs:element name="End" type="xs:unsignedShort" />
                                <xs:element name="Name" type="xs:string" />
                                <xs:element name="level" type="xs:string" />
                                <xs:element name="Grade" type="xs:string" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Hobbies">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Hobby">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Name" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== mercysho/CO458-XML/CV/CV.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="CV.xslt"?>

<CV xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="CV.xsd">
  <PersonalDetails>
    <FullName> Mercy Sholola </FullName>
    <Email>mercysholola@outlook.com</Email>
    <PhoneNumber>07910000000</PhoneNumber>
    <Photo>https://i.pinimg.com/originals/08/0f/02/080f02bde02255a84594839d90b20e56.jpg</Photo>
  </PersonalDetails>

  <Employment>
    <Job>
      <Start> 2019 </Start>
      <End>Current</End>
      <Company>Millennium Pharmacy</Company>
      <Duties>Pharmacist/ Sales assistant</Duties>
      <Description>Welcoming customers into the store,
      managing payment, dispensing patient medication</Description>
    </Job>
    <Job>
      <Start> 2019 </Start>
      <End>2019</End>
      <Company>National Career Service</Company>
      <Duties>Job Fair Assistant</Duties>
      <Description>
        Dircting customers where to go within the job fair,
        providing information regarding the workshops</Description>
    </Job>
    <Job>
      <Start> 2018 </Start>
      <End>2018</End>
      <Company>Lambeth College</Company>
      <Duties>IT Support assistant</Duties>
      <Description>
        Helping set up equipment, assisting to set up new equipment
      assisting IT technician</Description>
    </Job>
  </Employment>

  <Education>
    <Insitution name="The Grey Coat Hospital School">
      <Subjects>
        <Subject>
          <Start>2014</Start>
          <End>2029</End>
          <Name> Maths, English, Science, RE, German, DT, Music </Name>
          <level>GCSE</level>
          <Grade>A-C</Grade>
        </Subject>
      </Subjects>
    </Insitution>
    
    <Insitution name="City of Westminster College">
      <Subjects>
        <Subject>
          <Start>2019</Start>
          <End>2021</End>
          <Name> Informational Technology </Name>
          <level>BTEC Level 3</level>
          <Grade>Distinction-Merit-Merit</Grade>
        </Subject>
      </Subjects>
    </Insitution>

    <Insitution name="Buckinghamshire New University">
      <Subjects>
        <Subject>
          <Start>2021</Start>
          <End>2024</End>
          <Name>Computing and Web Development</Name>
          <level>BSc</level>
          <Grade>null</Grade>
        </Subject>
      </Subjects>
    </Insitution>
  </Education>

  <Hobbies>
    <Hobby>
      <Name> Singing </Name>
    </Hobby>
  </Hobbies>

</CV>
